---
University Paris 1 Panthéon-Sorbonne

Introduction to Machine Learning

Dr. Nourhène BEN RABAH

---


<h1 style="color: blue;"> Lab 1. Data Exploration with Pandas  </h1>


#### Here is the documentation for the [`DataFrame`](https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.html) data structure in Pandas.


#### You must send the completed notebook to Nourhene.Ben-Rabah@univ-paris1.fr. Please include LastName_FirstName_Lab1_IKSEM in your subject line.

---

<h2 style="color: blue;"> Part 1: Reading, Quick Exploration, and Selection</h2>

#### Step 0. Import the Pandas library


#### Step 1. Import the dataset

You will start by importing the file *cheese.csv*. To do this, use the [`read_csv`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) function.

In [24]:
import pandas as pd 

df = pd.read_csv("datasets/cheese.csv", sep=";")

#### Step 2. View the first and last rows

In [25]:
df.head(1)
df.tail(1)

,cheese,calories,sodium,calcium,lipides,retinol,folates,proteines,cholesterol,magnesium
28,Yaourtlaitent.nat.,70,91.0,215.7,3.4,42.9,2.9,4.1,13,14

#### Step 3.  
By looking at these rows, you probably noticed that the import didn’t go correctly. So, you will now import the dataset properly.    
You will use ';' as the delimiter and specify that the first row contains the column names.

You can then check once more.

#### Step 4. Check the data types of each column

The second thing to do is a quick check of the data types assigned by Pandas to each column during import, again to ensure that the import was successful.  Display the data type of all columns.

In [38]:
df.dtypes

cheese_name        str
calories         int64
sodium         float64
calcium        float64
lipides        float64
retinol        float64
folates        float64
proteines      float64
cholesterol      int64
magnesium        int64
dtype: object

#### Step 5. How many observations are in the dataset?

How many rows and columns are contained in our file?

In [27]:
rows, columns = df.shape
print(f"{rows} rows and {columns} columns")

29 rows and 10 columns

#### Step 6. What information is available about the first cheese in the dataset?

It's now time to use the most useful selection function: the [`iloc`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html) method.

In [33]:
df.iloc[0]

cheese_name    CarredelEst
calories               314
sodium               353.5
calcium               72.6
lipides               26.3
retinol               51.6
folates               30.3
proteines             21.0
cholesterol             70
magnesium               20
Name: 0, dtype: object

#### Step 7. Rename the variable `Cheeses` to `Cheeses_name`.

In [31]:
df = df.rename(columns={'cheese': 'cheese_name'}) #or adding inplace=true instead of reassigning
df.columns.tolist()[0]

'cheese_name'

#### Step 8. What cheeses are present in the dataset?

In [37]:
set(df["cheese_name"])

{'Babybel',
 'Beaufort',
 'Bleu',
 'Camembert',
 'Cantal',
 'CarredelEst',
 'Chabichou',
 'Chaource',
 'Cheddar',
 'Comte',
 'Coulomniers',
 'Edam',
 'Emmental',
 'Fr.chevrepatemolle',
 'Fr.fondu.45',
 'Fr.frais20nat.',
 'Fr.frais40nat.',
 'Maroilles',
 'Morbier',
 'Parmesan',
 'Petitsuisse40',
 'PontlEveque',
 'Pyrenees',
 'Reblochon',
 'Rocquefort',
 'SaintPaulin',
 'Tome',
 'Vacherin',
 'Yaourtlaitent.nat.'}

##### Step 9. Quick analysis of the information in our dataset

Use the [`describe`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html) and [`info`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html) functions to get some quick information about the variables in our dataframe:

In [39]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cheese_name  29 non-null     str
 1   calories     29 non-null     int64
 2   sodium       29 non-null     float64
 3   calcium      29 non-null     float64
 4   lipides      29 non-null     float64
 5   retinol      29 non-null     float64
 6   folates      29 non-null     float64
 7   proteines    29 non-null     float64
 8   cholesterol  29 non-null     int64
 9   magnesium    29 non-null     int64
dtypes: float64(6), int64(3), str(1)
memory usage: 2.4 KB

,calories,sodium,calcium,lipides,retinol,folates,proteines,cholesterol,magnesium
count,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000
mean,300.034483,210.086207,185.734483,24.158621,67.562069,13.010345,20.168966,74.586207,26.965517
std,91.914356,108.678923,72.528882,8.129642,24.163098,11.723339,6.959788,28.245755,11.318388
min,70.000000,22.000000,72.600000,3.400000,37.100000,1.200000,4.100000,10.000000,10.000000
25%,292.000000,140.000000,132.900000,23.400000,51.600000,4.900000,17.800000,70.000000,20.000000
50%,321.000000,223.000000,202.300000,26.300000,62.300000,6.400000,21.000000,80.000000,26.000000
75%,355.000000,276.000000,220.500000,29.100000,76.400000,21.100000,23.400000,90.000000,30.000000
max,406.000000,432.000000,334.600000,33.300000,150.500000,36.400000,35.700000,120.000000,51.000000

Based on these descriptions, can you determine the number of non-null elements in the dataset?

In [42]:
29

29

##### Step 10. Selection within a dataframe

###### a) We have seen how to select a column. Using similar syntax, select two columns of your choice.

In [53]:
df[["calories","proteines"]]
#df.loc[:, ["calories","proteines"]]

    calories  proteines
0        314       21.0
1        314       22.6
2        401       26.6
3        342       20.2
4        264       23.4
5        367       23.0
6        344       19.5
7        292       17.8
8        406       26.0
9        399       29.2
10       308       20.5
11       327       24.7
12       378       29.4
13       206       11.1
14       292       16.8
15        80        8.3
16       115        7.0
17       338       20.4
18       347       23.6
19       381       35.7
20       142        9.4
21       300       21.1
22       355       22.4
23       309       19.7
24       370       18.7
25       298       23.3
26       321       21.8
27       321       17.6
28        70        4.1

###### b) Using the [`loc`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) method, select and determine the cheeses with low calories (less than 100):

In [54]:
df.loc[df["calories"] < 100]

,cheese_name,calories,sodium,calcium,lipides,retinol,folates,proteines,cholesterol,magnesium
15,Fr.frais20nat.,80,41.0,146.3,3.5,50.0,20.0,8.3,10,11
28,Yaourtlaitent.nat.,70,91.0,215.7,3.4,42.9,2.9,4.1,13,14

###### c) Select only the names of these cheeses

In [58]:
df.loc[df["calories"] < 100]["cheese_name"].to_list()

['Fr.frais20nat.', 'Yaourtlaitent.nat.']

###### d) Now select the information describing the cheeses with less than 100 calories and more than 5 grams of protein.

In [71]:
df.loc[(df["calories"] < 100) & (df["proteines"] > 5) ]["cheese_name"].to_list()

[]

###### e) For these cheeses, select only their name and the number of proteins.

In [65]:
df.loc[(df["calories"] < 100) & (df["proteines"] > 5) ][["cheese_name","proteines"]]

       cheese_name  proteines
15  Fr.frais20nat.        8.3

###### f) Finally, create a new dataframe that will contain only the cheeses with calories greater than or equal to 100.

In [67]:
df = df.loc[df["calories"] >= 100]

##### Step 11. Creating new variables

We will create a new dietary column that indicates whether the cheese is suitable for a diet based on the criteria "calories < 100" and "proteins > 5"

In [69]:
df['dietetique'] = ((df['calories'] < 100) & (df['proteines'] > 5)).map({True: 'Yes', False: 'No'})

,cheese_name,calories,sodium,calcium,lipides,retinol,folates,proteines,cholesterol,magnesium,dietetique
0,CarredelEst,314,353.5,72.6,26.3,51.6,30.3,21.0,70,20,No
1,Babybel,314,238.0,209.8,25.1,63.7,6.4,22.6,70,27,No
2,Beaufort,401,112.0,259.4,33.3,54.9,1.2,26.6,120,41,No
3,Bleu,342,336.0,211.1,28.9,37.1,27.5,20.2,90,27,No
4,Camembert,264,314.0,215.9,19.5,103.0,36.4,23.4,60,20,No
5,Cantal,367,256.0,264.0,28.8,48.8,5.7,23.0,90,30,No
6,Chabichou,344,192.0,87.2,27.9,90.1,36.3,19.5,80,36,No
7,Chaource,292,276.0,132.9,25.4,116.4,32.5,17.8,70,25,No
8,Cheddar,406,172.0,182.3,32.5,76.4,4.9,26.0,110,28,No
9,Comte,399,92.0,220.5,32.4,55.9,1.3,29.2,120,51,No
10,Coulomniers,308,222.0,79.2,25.6,63.6,21.1,20.5,80,13,No
11,Edam,327,148.0,272.2,24.7,65.7,5.5,24.7,80,44,No
12,Emmental,378,60.0,308.2,29.4,56.3,2.4,29.4,110,45,No
13,Fr.chevrepatemolle,206,160.0,72.8,18.5,150.5,31.0,11.1,50,16,No
14,Fr.fondu.45,292,390.0,168.5,24.0,77.4,5.5,16.8,70,20,No
16,Fr.frais40nat.,115,25.0,94.8,7.8,64.3,22.6,7.0,30,10,No
17,Maroilles,338,311.0,236.7,29.1,46.7,3.6,20.4,90,40,No
18,Morbier,347,285.0,219.0,29.5,57.6,5.8,23.6,80,30,No
19,Parmesan,381,240.0,334.6,27.5,90.0,5.2,35.7,80,46,No
20,Petitsuisse40,142,22.0,78.2,10.4,63.4,20.4,9.4,20,10,No
21,PontlEveque,300,223.0,156.7,23.4,53.0,4.0,21.1,70,22,No
22,Pyrenees,355,232.0,178.9,28.0,51.5,6.8,22.4,90,25,No
23,Reblochon,309,272.0,202.3,24.6,73.1,8.1,19.7,80,30,No
24,Rocquefort,370,432.0,162.0,31.2,83.5,13.3,18.7,100,25,No
25,SaintPaulin,298,205.0,261.0,23.3,60.4,6.7,23.3,70,26,No
26,Tome,321,252.0,125.5,27.3,62.3,6.2,21.8,80,20,No
27,Vacherin,321,140.0,218.0,29.3,49.2,3.7,17.6,80,30,No

<h2 style="color: blue;">Part 2: Identification and Handling of Missing Values</h2>

Now, we will address the handling of a DataFrame with issues. You will import the CSV file named 'cheese_V2'.

In [73]:
import pandas as pd 

df2 = pd.read_csv("datasets/cheese_V2.csv", sep=";")

##### Step 12: Identification and Handling of Missing Values

While exploring your DataFrame, you likely noticed an empty column named **'unnamed'** and rows containing null values. You can use methods to check for missing values such as:
- isna() or isnull()
- Visualize the distribution of missing values.

In [ ]:
'''df2.isna()
df2.isnull()'''

'''Count the missing values for each column
df2.isna().sum()'''

'''import missingno as msno
# Visualize the missing values in the DataFrame
msno.matrix(df2)'''

'import missingno as msno\n# Visualize the missing values in the DataFrame\nmsno.matrix(df2)'

To handle missing values, several options are available to you:

##### 1. **Deletion of rows or columns**
   You can choose to delete rows or columns containing missing values. This can be useful if the missing data is minimal and its removal does not significantly affect the analysis.

##### 2. **Filling missing values (imputation)**
   Imputation involves replacing missing values (or NaNs) with estimated or calculated values. Several techniques are available for imputation:
   - **Imputation with a constant value**: Replace missing values with a fixed value of your choice.
   - **Imputation with the mean**: Replace missing values with the mean of the column.
   - **Imputation with the median**: Use the median to replace missing values, which can be more robust against outliers.
   - **Imputation with the most frequent value (mode)**: Replace missing values with the most frequent value in the column.
   - **Imputation with regression**: Use a **regression** model to predict missing values based on other variables in the dataset. This can be more effective when missing values are related to other features of the data.



---

##### Choosing the imputation method based on the type of data

The choice of method depends on the **context** of your data and the **objective** of your analysis. Here are some guidelines based on the type of data:

- **Numerical data**: For continuous variables such as age, income, or temperature, methods like **mean**, **median**, or even **regression** imputation may be appropriate.
  
- **Categorical data**: For non-numeric variables, such as categories (e.g., gender or colors), imputation with the **most frequent value** or **regression** (based on explanatory variables) may be more effective.



###### a) Deletion of rows or columns

In [ ]:
df2.dropna(axis=1, inplace=True) 
df2

In [ ]:
# Mean imputation for missing calorie values
mean_column = df2['calories'].mean()  
df2['calories'].fillna(mean_column, inplace=True)
df2.tail(5)

###### b) Filling missing values with the mean

- Imputation with standard deviation for sodium
- Imputation with 1 for fats
- Imputation with the most frequent value for fotales

<h2 style="color: blue;"> Correlation matrix</h2>


A correlation matrix is a table that shows the correlation (linear relationship) between multiple variables in a dataset. Each value in the matrix represents the **strength** and **direction** of the relationship between two variables.

Correlations are often measured using the **Pearson correlation coefficient**, which ranges from **-1 to 1**:

- **1**: Perfect positive correlation (when one variable increases, the other increases proportionally).
- **-1**: Perfect negative correlation (when one variable increases, the other decreases proportionally).
- **0**: No correlation (the variables are independent).

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Compute the correlation matrix
corr_matrix = df2.corr()

# Visualize with a heatmap
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', vmin=-1, vmax=1)
plt.title("Correlation Matrix")
plt.show()

<h2 style="color: blue;"> Part 4. let's play </h2>

- Import the IRIS dataset from the following URL: [`IRIS`] (https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv)
- Display the first and last few rows of the DataFrame.
- Determine the number of rows and columns in the dataset.
- Display the value in the third row of the "sepal_width" column.
- Display the entire third row of the DataFrame.
- Calculate and display the mean of the "sepal_length" column.
- Calculate and display the standard deviation of the "sepal_length" column.
- Find and display the minimum value in the "sepal_length" column.
- Check for missing values in the dataset.
- Set the values of rows 10 to 29 in the "petal_length" column to NaN.
- Replace the NaN values in the "petal_length" column with 1.0.
- Set the first three rows of the DataFrame to NaN.
- Remove all rows containing NaN values from the DataFrame : [`dropna`](https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.dropna.html)
- Rename the "species" column to "class".

#### Exercice 2.
Objective: Create a Pandas DataFrame from the two variables declared below. The keys of the dictionary exam_data correspond to the column names of the DataFrame. The list of strings labels corresponds to the index of the DataFrame.

Explore then this dataframe and decide on an appropriate strategy to handle missing data

In [ ]:
import numpy as np
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['z', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df=pd.DataFrame (exam_data, labels)

#### Exercice 3.
Objective: Work with the Open Food Facts dataset to load and explore the data.
- Step 1: Navigate to Open Food Facts Dataset on Kaggle : https://www.kaggle.com/datasets/openfoodfacts/world-food-facts
   
- Step 2: Download the dataset to your computer and unzip it.
   
- Step 3: Use the TSV (Tab-Separated Values) file and assign it to a DataFrame named food using the following code:

In [ ]:
food.shape
food.shape[0]
food.columns
food.columns[104]

Part 5: Your Turn Again

- Explore the VenteAgence dataset.

- Repeat all the data exploration steps.

#### Discovering Dates and Extracting More Information from Dates.

Once a column is converted to a date using to_datetime, you can extract various pieces of information from its values.

The column "DATE FACTURE" contains dates. Therefore, it needs to be converted using to_datetime.

In [ ]:
#dfFactures['DATE FACTURE'] = pnd.to_datetime(dfFactures['DATE FACTURE'])

From this point, we will be able to extract many useful pieces of information:
- Day
- Month
- Year
- Day of the week
- Day of the week in text
- Month in text

In [ ]:
'''dfFactures['JOUR FACTURE'] = dfFactures['DATE FACTURE'].dt.day
dfFactures['MOIS FACTURE'] = dfFactures['DATE FACTURE'].dt.month
dfFactures['ANNEE FACTURE'] = dfFactures['DATE FACTURE'].dt.year
dfFactures['JOUR SEMAINE'] = dfFactures['DATE FACTURE'].dt.weekday
dfFactures['NOM JOUR'] = dfFactures['DATE FACTURE'].dt.day_name()
dfFactures['NOM MOIS'] = dfFactures['DATE FACTURE'].dt.month_name()

dfFactures['SEMAINE ANNEE'] = dfFactures['DATE FACTURE'].dt.isocalendar().week

dfFactures.sample(5)'''

If we try to retrieve the time from the data in the "DATE_FACTURE" column, we won't be able to, because this information is missing from the original data.

In [ ]:
#dfFactures['DATE FACTURE'].dt.time